#!/bin/bash

module load Mambaforge
conda activate dannce-dev

# SQLITE3_DB="/n/holylabs/LABS/olveczky_lab/Lab/dannce-dev/newsdannce/apps/gui_be/instance_data/db.sqlite3"

echo "SET SQLITE3_DB env variable before running"
exit -1

conda run -n dannce-dev --no-capture-output sqlite3 $SQLITE3_DB


