#!/bin/bash

module load Mambaforge
conda run -n dannce-dev --no-capture-output python -m fastapi dev ./app/main.py --host 0.0.0.0

# this would go in script.sh.erb
# any options can be passed thru the form
# would also include sbatch args, etc.
