#!/bin/bash

# required env varibales
echo "FASTAPI_PORT=$FASTAPI_PORT"
echo "FLOWER_PORT=$FLOWER_PORT"
echo "RABBITMQ_NODE_PORT=$RABBITMQ_NODE_PORT"


conda run -n dannce-dev --no-capture-output python -m fastapi run ./app/main.py --port=$FASTAPI_PORT --host=0.0.0.0

# (trap 'kill 0' SIGINT; \
#     conda run -n dannce-dev --no-capture-output rabbitmq-server &\
#     conda run -n dannce-dev --no-capture-output celery -A taskqueue.celery worker --loglevel=INFO &\
#     conda run -n dannce-dev --no-capture-output celery -A taskqueue.celery flower --port=$FLOWER_PORT --loglevel=INFO &\
#     conda run -n dannce-dev --no-capture-output python -m fastapi run ./app/main.py --port=$FASTAPI_PORT
# )   

