### Config file based off sdannce repo: demo/2021_..._M6/io.yaml
### SOCIAL COM EXPERIMENTS **
# this dir will store COM training artefacts (logs, saved state, etc.)
com_train_dir: ./COM/train02

# this dir will store COM prediction output data (COM positions, metadata, etc.)
com_predict_dir: ./COM/predict02

# Path to .pth weights to use for COM prediction
com_exp:
  - label3d_file: "/n/holylfs02/LABS/olveczky_lab/Everyone/dannce_rig/dannce_ephys/art/2020_12_21_1/20201221_163226_Label3D_dannce.mat"
  - label3d_file: "/n/holylfs02/LABS/olveczky_lab/Everyone/dannce_rig/dannce_ephys/bud/2021_06_21_1/20210622_154326_Label3D_dannce.mat"

### SDANNCE EXPERIMENTS **
dannce_train_dir: ./SDANNCE/train02/
dannce_predict_dir: ./SDANNCE/predict02/
dannce_predict_model:

exp:
  - label3d_file: "../2021_07_06_M3_M6/ANNOT_Label3D_B_dannce.mat"
    com_file: "../2021_07_06_M3_M6/COM/predict01/instance0com3d.mat"
  - label3d_file: "../2021_07_06_M3_M6/ANNOT_Label3D_R_dannce.mat"
    com_file: "../2021_07_06_M3_M6/COM/predict01/instance1com3d.mat"
  - label3d_file: "../2021_07_07_M5_M1/ANNOT_Label3D_B_dannce.mat"
    com_file: "../2021_07_07_M5_M1/COM/predict01/instance0com3d.mat"
  - label3d_file: "../2021_07_07_M5_M1/ANNOT_Label3D_R_dannce.mat"
    com_file: "../2021_07_07_M5_M1/COM/predict01/instance0com3d.mat"
