### basic ###
io_config: io.yaml
random_seed: 1024

### data ###
camnames: ["Camera1", "Camera2", "Camera3", "Camera4", "Camera5", "Camera6"]
n_instances: 1 # number of animals. >=1 is social training. default=1
n_channels_out: 1 # number of channels to predect i.e. number of markers. default=1
#  VERY IMPORTANT THAT HEIGHT & WIDTH ARE DIVISIBLE BY 128 (i.e. downfac * 2^4)!
crop_height: [0, 1152]
crop_width: [0, 1920]
downfac: 8 # default=4
# sigma: 30 # default=30

### training options
train_mode: new # train from scratch. NO DEFAULT (TODO: PROBABLY SET ONE?)
# Possible trian modes for COM:
#   - "new": train from scratch
#   - "finetune": fine tune from (COM) finetune weights file
#   - "continued": continue training from (DANNCE) finetune weights file (??)
# com_finetune_weights: #./COM/weights
num_validation_per_exp: 2 # unknown
batch_size: 4 # default=6
epochs: 20 # default=100
lr: 5e-5 # default=5e-5
loss:
  MSELoss:
    loss_weight: 1.0
metric: []
save_period: 5

# If true, saves plots of the training labels overlaid on images
#debug: True

# If present, write the confidence map output and image/COM overlays to disk during prediction
#com_debug: Camera5

### prediction ###
max_num_samples: max
# ----------------------------------------- #
# ------ OLD CONFIG FROM DANNCE ----------- #
# ----------------------------------------- #

# volumetric representation
# (large) male rats: ~120
# female rats: ~80
# vmin: -120
# vmax: 120
# nvox: 80
# interp: nearest

# ### train ###
# batch_size: 4
# epochs: 100
# lr: 0.0001
# train_mode: new

# COM_augmentation: {}

# num_validation_per_exp: 4
# save_period: 10
# data_split_seed: 1024

# ### architecture ###
# expval: True
# net_type: "compressed_dannce"
# n_channels_in: 3
# n_channels_out: 23
# new_n_channels_out: 23
# n_views: 6

# ### loss ###
# metric: ['euclidean_distance_3D']
# loss:
#     L1Loss:
#       loss_weight: 1.0

# ### data augmentation ###
# medfilt_window: 30
# rand_view_replace: True
# n_rand_views: 6
# mirror_augmentation: False
# left_keypoints: [1, 7, 8, 9, 10, 15, 16, 17, 18]
# right_keypoints: [2, 11, 12, 13, 14, 19, 20, 21, 22]

# augment_hue: False
# augment_brightness: False
# augment_bright_val: 0.01

# ### predictions ###
# max_num_samples: max

