name: dannce-dev
channels:
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy<2.0
  - ca-certificates
  - openssl
  - scipy
  - ipykernel
  - x264
  - certifi
  - matplotlib
  - pip
  - rabbitmq-server
  - ffmpeg
  - pip:
      - opencv-python-headless
      - ruamel.yaml
      - fastapi[standard]
      - sqlmodel
      - ruamel.yaml.string
      - pydantic_settings
      - celery
      - flower
      - jinja2
      - docker
      - python-multipart
