### basic ###
io_config: io.yaml
camnames: ["Camera1", "Camera2", "Camera3", "Camera4", "Camera5", "Camera6"]
random_seed: 1024

### data ###
crop_height: [0, 1200]
crop_width: [0, 1920]

# volumetric representation
vol_size: 240

nvox: 80
interp: nearest

### train ###
batch_size: 4
epochs: 100
lr: 0.0001
train_mode: new

COM_augmentation: {}

num_validation_per_exp: 4
save_period: 10
data_split_seed: 1024

### architecture ###
expval: True
net_type: "compressed_dannce"
n_channels_in: 3
n_channels_out: 23
new_n_channels_out: 23
n_views: 6

### loss ###
metric: ["euclidean_distance_3D"]
loss:
  L1Loss:
    loss_weight: 1.0

### data augmentation ###
medfilt_window: 30
rand_view_replace: True
n_rand_views: 6
mirror_augmentation: False

### predictions ###
max_num_samples: max
