name: dannce-dev
channels:
  - defaults
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - ca-certificates
  - openssl
  - scipy
  - ipykernel
  - jupyterlab
  - imageio-ffmpeg
  - x264
  - certifi
  - matplotlib
  - pip
  - gitpython
  - jinja2
  - pip:
      - opencv-python
      - pyside6
      - ruamel.yaml
      - fastapi[standard]
      - SQLAlchemy
      - sqlmodel
      - ruamel.yaml.string
      - av


